name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./ci-cd-demo  # <-- Aquí le dices dónde está el pom.xml

      - name: Run Tests
        run: mvn test
        working-directory: ./ci-cd-demo  # <-- Igual aquí
